Repository MetaFam/TheGame, pull requests merged in 2020-12, with the labels that each got.

#195 Backend Guide
  README.md
  guides/BACKEND.md
Labels: backend, good first issue

#223 MyMeta SEED Ticker
  packages/web/components/PageHeader.tsx
  packages/web/components/Ticker.tsx
  packages/web/package.json
Labels: approved-with-suggestions

#236 Refactor PlayerPage and remove mock components
  packages/design-system/src/index.ts
  packages/web/assets/main-background.jpg
  packages/web/components/Container.tsx
  packages/web/components/Player/Box/PlayerCollab.tsx
  packages/web/components/Player/Box/PlayerHero.tsx
  packages/web/components/Player/Section/PlayerAchievements.tsx
  packages/web/components/Player/Section/PlayerAddSection.tsx
  packages/web/components/Player/Section/PlayerCollab.tsx
  packages/web/components/Player/Section/PlayerContactButtons.tsx
  packages/web/components/Player/Section/PlayerGallery.tsx
  packages/web/components/Player/Section/PlayerHero.tsx
  packages/web/components/Player/Section/PlayerMemberships.tsx
  packages/web/components/Player/Section/PlayerSection.tsx
  packages/web/components/Player/Section/PlayerSkills.tsx
  packages/web/components/Setup/SetupProfile.tsx
  packages/web/pages/index.tsx
  packages/web/pages/player/[username].tsx
  packages/web/pages/profile/success.tsx
Labels: ready-for-review

#237 Add LoadingState and fix empty state for player page
  packages/design-system/src/LoadingState.tsx
  packages/design-system/src/index.ts
  packages/web/components/Player/Section/PlayerSection.tsx
  packages/web/components/Player/Section/PlayerSkills.tsx
  packages/web/pages/player/[username].tsx
Labels: ready-for-review

#218 Frontend Guide
  README.md
  guides/FRONTEND.md
Labels: frontend, needs-changes

#234 MyMeta - App Drawer
  packages/web/components/LoginButton.tsx
  packages/web/components/MobileFooter.tsx
  packages/web/components/PageHeader.tsx
  packages/web/package.json
  packages/web/pages/_app.tsx
  packages/web/pages/profile/setup.tsx
  packages/web/pages/profile/success.tsx
  packages/web/pages/register.tsx
  packages/web/pages/welcome.tsx
  packages/web/public/assets/drawer/box.button.bg.png
  packages/web/public/assets/drawer/calendar.png
  packages/web/public/assets/drawer/desktop-box.png
  packages/web/public/assets/drawer/desktop.gradient.png
  packages/web/public/assets/drawer/discord.png
  packages/web/public/assets/drawer/forum.png
  packages/web/public/assets/drawer/github.png
  packages/web/public/assets/drawer/guilds.png
  packages/web/public/assets/drawer/leaderboard.png
  packages/web/public/assets/drawer/library.png
  packages/web/public/assets/drawer/metaview.png
  packages/web/public/assets/drawer/newsletter.png
  packages/web/public/assets/drawer/players.png
  packages/web/public/assets/drawer/quests.png
  packages/web/public/assets/drawer/raids.png
  packages/web/public/assets/drawer/seed_pool.png
  packages/web/public/assets/drawer/seedmarket.png
  packages/web/public/assets/drawer/twitter.png
  packages/web/public/assets/emojis/crossed-swords.png
  packages/web/public/assets/logo.png
  packages/web/public/assets/metagame.png
  packages/web/utils/drawerItems.ts
  yarn.lock
Labels: frontend, needs-changes

#231 Feature/add timezone frontend
  packages/@types/react-timezone-select/index.d.ts
  packages/@types/spacetime-informal/index.d.ts
  packages/design-system/package.json
  packages/design-system/src/SelectSearch.tsx
  packages/design-system/src/SelectTimeZone.tsx
  packages/design-system/src/index.ts
  packages/web/components/Player/PlayerTimeZone.tsx
  packages/web/components/Player/Section/PlayerCollab.tsx
  packages/web/components/Setup/SetupAvailability.tsx
  packages/web/components/Setup/SetupProfile.tsx
  packages/web/components/Setup/SetupSkills.tsx
  packages/web/components/Setup/SetupTimeZone.tsx
  packages/web/contexts/SetupContext.tsx
  packages/web/graphql/fragments.ts
  packages/web/graphql/mutations/updateAboutYou.ts
  packages/web/graphql/mutations/updateProfile.ts
  packages/web/graphql/mutations/updateSkills.ts
  packages/web/package.json
  packages/web/utils/dateHelpers.ts
  packages/web/utils/setupOptions.tsx
  packages/web/utils/skillHelpers.ts
  yarn.lock
Labels: needs-changes
