Repository MetaFam/TheGame, pull requests merged in 2021-01, with the labels that each got.

#304 [MetaMaps] Fix context menu
  hasura/metadata/tables.yaml
  packages/metamaps/components/index/Index.create.tsx
  packages/metamaps/components/index/Index.items.tsx
  packages/metamaps/components/map/Map.container.tsx
  packages/metamaps/components/map/Map.context.tsx
  packages/metamaps/components/map/Map.edit.tsx
  packages/metamaps/components/map/Map.popover.tsx
  packages/metamaps/components/map/Map.profile.tsx
  packages/metamaps/components/map/Map.title.tsx
  packages/metamaps/components/map/styles/Map.context.styles.tsx
  packages/metamaps/components/map/styles/Map.popover.styles.tsx
  packages/metamaps/pages/[author_address]/map/[id].tsx
  packages/metamaps/pages/_app.tsx
  packages/metamaps/redux/Reducer.map.state.tsx
Labels: bug

#305 [MyMeta] Use responsive units on the header and footer
  packages/web/components/MobileFooter.tsx
  packages/web/components/PageHeader.tsx
  packages/web/pages/player/[username].tsx
  packages/web/public/assets/drawer/desktop.gradient.png
Labels: frontend

#314 Remove unused codegen stuff and update Hasura to latest version
  README.md
  guides/BACKEND.md
  hasura/Dockerfile
  packages/codegen/customFragments.ts
  packages/codegen/graphql-codegen-gql.yaml
  packages/codegen/graphql-codegen-typescript.yaml
  packages/codegen/package.json
  yarn.lock
Labels: ready-for-review

#315 Use exact versions in package.json files
  package.json
  packages/backend/package.json
  packages/codegen/package.json
  packages/design-system/package.json
  packages/metamaps/package.json
  packages/utils/package.json
  packages/web/package.json
  yarn.lock
Labels: ready-for-review

#316 Move schema.graphql to root of project and delete codegen package
  .graphqlconfig
  package.json
  packages/backend/codegen.yml
  packages/codegen/package.json
  packages/web/codegen.yml
  schema.graphql
Labels: ready-for-review
