Repository MetaFam/TheGame, pull requests merged in 2021-02, with the labels that each got.

#318 Codegen wasn't completely removed
  docker-compose.yml
  docker/backend/Dockerfile
  package.json
Labels: bug, ready-for-review

#294 Cross Browser Gradient for App Drawer
  .gitignore
  packages/design-system/package.json
  packages/design-system/src/BoxedNextImage.tsx
  packages/design-system/src/index.ts
  packages/web/components/LoginButton.tsx
  packages/web/components/MobileFooter.tsx
  packages/web/components/PageHeader.tsx
  packages/web/lib/hooks.ts
  packages/web/package.json
  packages/web/pages/guild/[guildname].tsx
  packages/web/pages/player/[username].tsx
  packages/web/public/assets/drawer/desktop-box.png
  packages/web/public/assets/drawer/desktop.gradient.bottom.png
  packages/web/public/assets/drawer/desktop.gradient.png
  yarn.lock
Labels: frontend, ready-for-review

#340 Quest create handlers
  hasura/metadata/actions.graphql
  hasura/metadata/actions.yaml
  packages/backend/src/config.ts
  packages/backend/src/handlers/actions/quests/createCompletion/createCompletion.ts
  packages/backend/src/handlers/actions/quests/createCompletion/handler.ts
  packages/backend/src/handlers/actions/quests/createQuest/createQuest.ts
  packages/backend/src/handlers/actions/quests/createQuest/handler.ts
  packages/backend/src/handlers/actions/quests/createQuest/permissions.ts
  packages/backend/src/handlers/actions/quests/routes.ts
  packages/backend/src/handlers/actions/quests/updateCompletion/handler.ts
  packages/backend/src/handlers/actions/quests/updateCompletion/updateCompletion.ts
  packages/backend/src/handlers/actions/routes.ts
  packages/backend/src/handlers/actions/types.ts
  packages/backend/src/handlers/actions/updateBoxProfile/updateVerifiedAccounts.ts
  packages/backend/src/handlers/auth-webhook/handler.ts
  packages/backend/src/handlers/graphql/mutations.ts
  packages/backend/src/handlers/graphql/queries.ts
  packages/backend/src/lib/abis/ERC20.json
  packages/backend/src/lib/ethereum.ts
  packages/backend/src/lib/hasuraClient.ts
  packages/utils/package.json
  packages/utils/src/index.ts
  packages/utils/src/numbers.ts
  schema.graphql
  yarn.lock
Labels: backend, hasura
