Repository MetaFam/TheGame, pull requests merged in 2021-09, with the labels that each got.

#806 [MyMeta] Add Architecture Diagram
  guides/CONTRIBUTING.md
  guides/DESCRIPTIVE_C4.MD
  guides/README.md
  guides/architecture.svg
Labels: ready-for-review

#807 Create player skill rank migration (v2)
  hasura/metadata/tables.yaml
  hasura/migrations/1626994599013_add_rank_to_skill_table/up.sql
  hasura/migrations/1626996347721_modify_primarykey_public_player_skill/down.sql
  hasura/migrations/1626996347721_modify_primarykey_public_player_skill/up.sql
  hasura/migrations/1626996361256_modify_primarykey_public_player_skill/down.sql
  hasura/migrations/1626996361256_modify_primarykey_public_player_skill/up.sql
  packages/web/components/Setup/SetupUsername.tsx
  schema.graphql
Labels: backend, hasura

#758 Feature/mega menu alt
  packages/design-system/src/index.ts
  packages/design-system/src/theme/index.ts
  packages/web/assets/menuIcon/alliances.png
  packages/web/assets/menuIcon/asketh.png
  packages/web/assets/menuIcon/contribute.png
  packages/web/assets/menuIcon/discord.png
  packages/web/assets/menuIcon/forum.png
  packages/web/assets/menuIcon/grants.png
  packages/web/assets/menuIcon/guilds.png
  packages/web/assets/menuIcon/invest.png
  packages/web/assets/menuIcon/learn.png
  packages/web/assets/menuIcon/metagamewiki.png
  packages/web/assets/menuIcon/patrons.png
  packages/web/assets/menuIcon/playbooks.png
  packages/web/assets/menuIcon/players.png
  packages/web/assets/menuIcon/quests.png
  packages/web/assets/menuIcon/raids.png
  packages/web/assets/menuIcon/roles.png
  packages/web/assets/menuIcon/seedearned.png
  packages/web/assets/menuIcon/seeds.png
  packages/web/assets/menuIcon/thegreathouses.png
  packages/web/assets/menuIcon/welcometometagame.png
  packages/web/assets/menuIcon/xpearned.png
  packages/web/assets/search-icon.svg
  packages/web/assets/seed-icon.svg
  packages/web/assets/xp-star.svg
  packages/web/components/LoginButton.tsx
  packages/web/components/MegaMenu.tsx
  packages/web/components/PlayerStatsBar.tsx
  packages/web/pages/_app.tsx
  packages/web/utils/menuLinks.ts
Labels: WIP

#815 Fix internal MegaMenu links
  packages/web/utils/menuLinks.ts
Labels: frontend, bug-fix

#785 added a frequently asked question about Lerna
  README.md
Labels: ready-for-review

#801 added forLoginDisplay variable
  packages/web/components/LoginButton.tsx
  packages/web/components/Patron/PatronTile.tsx
  packages/web/components/Player/PlayerContacts.tsx
  packages/web/components/Player/PlayerTile.tsx
  packages/web/components/Player/PlayerTileMemberships.tsx
  packages/web/graphql/fragments.ts
  packages/web/graphql/getMe.ts
  packages/web/graphql/getPatrons.ts
  packages/web/graphql/getPlayer.ts
  packages/web/graphql/getPlayers.ts
  packages/web/graphql/getQuest.ts
  packages/web/lib/hooks/index.ts
Labels: hasura, ready-for-review

#845 Added requestPolicy option to useUser hook
  packages/web/lib/hooks/index.ts
  packages/web/pages/profile/setup/skills.tsx
Labels: bug-fix
