Repository MetaFam/TheGame, pull requests merged in 2021-06, with the labels that each got.

#599 Add github secret to staging-backend env
  render.yaml
Labels: ready-for-review

#603 Fix token config in render.yaml
  render.yaml
Labels: ready-for-review

#598 Release develop branch to prod
  .github/workflows/PR-CI.yml
  README.md
  hasura/Dockerfile
  package.json
  packages/@types/sourcecred/index.d.ts
  packages/backend/package.json
  packages/backend/src/config.ts
  packages/backend/src/handlers/actions/migrateSourceCredAccounts/handler.ts
  packages/backend/src/lib/sourcecredLedger.ts
  packages/design-system/package.json
  packages/discord-bot/package.json
  packages/utils/package.json
  packages/utils/src/constants.ts
  packages/web/package.json
  render.yaml
  yarn.lock
Labels: WIP

#625 Added contribution guide
  guides/CONTRIBUTING.md
Labels: WIP, help wanted

#626 allow aggregations in player table
  hasura/metadata/tables.yaml
Labels: backend, ready-for-review

#639 Merge master into develop
  packages/web/assets/colors/Ambition.svg
  packages/web/assets/colors/Balance.svg
  packages/web/assets/colors/Wisdom.svg
  packages/web/components/Player/ColorBar.tsx
  packages/web/graphql/getPersonalityInfo.ts
Labels: ready-for-review

#640 Setup action to nightly merge master into develop
  .github/workflows/nightly-merge.yml
Labels: ready-for-review

#637 Use environment variable for SourceCred ledger branch
  packages/backend/src/config.ts
  packages/backend/src/lib/sourcecredLedger.ts
  packages/discord-bot/src/config.ts
  packages/discord-bot/src/sourcecred.ts
  render.yaml
Labels: ready-for-review

#596 updates to player filters
  packages/design-system/src/MetaFilterSelect.tsx
  packages/design-system/src/MetaSelect.tsx
  packages/design-system/src/SelectSearch.tsx
  packages/design-system/src/index.ts
  packages/design-system/src/theme/colors.ts
  packages/web/components/Player/PlayerFilter.tsx
  packages/web/components/Setup/SetupSkills.tsx
  packages/web/graphql/fragments.ts
  packages/web/graphql/getPlayers.ts
  packages/web/graphql/getSkills.ts
  packages/web/lib/hooks/players.ts
  packages/web/pages/players.tsx
  packages/web/utils/skillHelpers.ts
Labels: frontend, ready-for-review
