Repository MetaFam/TheGame, pull requests merged in 2021-03, with the labels that each got.

#362 updated backend for brightId
  hasura/metadata/tables.yaml
  packages/backend/src/config.ts
  packages/backend/src/handlers/remote-schemas/resolvers/brightId/resolver.ts
  packages/backend/src/handlers/remote-schemas/schema.ts
  packages/backend/src/handlers/remote-schemas/typeDefs.ts
  packages/backend/src/handlers/remote-schemas/types/uuid.ts
  schema.graphql
Labels: backend, ready-for-review

#361 setup brightId verified labels
  .env.sample
  packages/backend/src/config.ts
  packages/backend/src/handlers/remote-schemas/resolvers/brightId/resolver.ts
  packages/design-system/src/icons/BrightIdIcon.tsx
  packages/design-system/src/icons/index.ts
  packages/design-system/src/index.ts
  packages/design-system/src/theme/colors.ts
  packages/web/components/Player/PlayerTile.tsx
  packages/web/components/Player/Section/PlayerBrightId.tsx
  packages/web/components/Player/Section/PlayerGallery.tsx
  packages/web/components/Player/Section/PlayerHero.tsx
  packages/web/config.ts
  packages/web/contexts/Web3Context.tsx
  packages/web/graphql/fragments.ts
  packages/web/graphql/types.ts
  packages/web/lib/hooks/brightId.ts
  packages/web/lib/hooks/index.ts
  packages/web/lib/hooks/opensea.ts
  packages/web/package.json
  yarn.lock
Labels: frontend, ready-for-review

#379 fixed seed price & login button not showing on mobile
  packages/web/components/PageHeader.tsx
Labels: frontend, ready-for-review

#380 added token balance from seed-graph
  hasura/metadata/tables.yaml
  packages/backend/codegen.yml
  packages/backend/src/config.ts
  packages/backend/src/handlers/remote-schemas/resolvers/getTokenBalance/queries.ts
  packages/backend/src/handlers/remote-schemas/resolvers/getTokenBalance/resolver.ts
  packages/backend/src/handlers/remote-schemas/schema.ts
  packages/backend/src/handlers/remote-schemas/typeDefs.ts
  packages/backend/src/lib/seedGraphClient.ts
Labels: backend, ready-for-review

#388 moved brightId verified tag to contacts
  packages/design-system/src/index.ts
  packages/design-system/src/theme/colors.ts
  packages/web/components/Player/PlayerContacts.tsx
  packages/web/components/Player/PlayerTile.tsx
  packages/web/components/Player/Section/PlayerBrightId.tsx
  packages/web/lib/hooks/useCopyToClipboard.ts
  packages/web/package.json
  yarn.lock
Labels: frontend, ready-for-review

#399 [MyMeta] updated seed-balances remote schema logic
  hasura/metadata/tables.yaml
  packages/backend/codegen.yml
  packages/backend/src/handlers/remote-schemas/resolvers/getTokenBalance/queries.ts
  packages/backend/src/handlers/remote-schemas/resolvers/getTokenBalance/resolver.ts
  packages/backend/src/handlers/remote-schemas/resolvers/seedGraph/queries.ts
  packages/backend/src/handlers/remote-schemas/resolvers/seedGraph/resolver.ts
  packages/backend/src/handlers/remote-schemas/schema.ts
  packages/backend/src/handlers/remote-schemas/typeDefs.ts
  schema.graphql
Labels: backend, ready-for-review

#410 added seed-graph as a new remote schema
  packages/backend/src/handlers/remote-schemas/resolvers/seedGraph/queries.ts
  packages/backend/src/handlers/remote-schemas/resolvers/seedGraph/resolver.ts
  packages/backend/src/handlers/remote-schemas/schema.ts
  packages/backend/src/handlers/remote-schemas/typeDefs.ts
  schema.graphql
Labels: backend, ready-for-review

#415 Merge dependencies
  .eslintrc.json
  package.json
  packages/backend/package.json
  packages/backend/src/handlers/triggers/handler.ts
  packages/backend/src/handlers/triggers/updateDiscordRole.ts
  packages/backend/src/lib/ethereum.ts
  packages/backend/src/lib/rankHelpers.ts
  packages/design-system/package.json
  packages/design-system/src/icons/index.ts
  packages/design-system/src/index.ts
  packages/metamaps/components/Circle.tsx
  packages/metamaps/components/Container.tsx
  packages/metamaps/components/Image.tsx
  packages/metamaps/components/Line.tsx
  packages/metamaps/components/Loading.tsx
  packages/metamaps/components/Menu.tsx
  packages/metamaps/components/Popup.tsx
  packages/metamaps/components/Square.tsx
  packages/metamaps/components/ThreeBox.tsx
  packages/metamaps/pages/_app.tsx
  packages/metamaps/pages/index.tsx
  packages/metamaps/redux/Reducer.tsx
  packages/utils/src/index.ts
  packages/web/components/Setup/SetupAvailability.tsx
  packages/web/components/Setup/SetupMemberships.tsx
  packages/web/components/Setup/SetupPersonalityType.tsx
  packages/web/components/Setup/SetupPlayerType.tsx
  packages/web/components/Setup/SetupProfile.tsx
  packages/web/components/Setup/SetupTimeZone.tsx
  packages/web/components/Setup/SetupUsername.tsx
  packages/web/contexts/SetupContext.tsx
  packages/web/package.json
  packages/web/pages/_app.tsx
  packages/web/pages/player/[username].tsx
  packages/web/pages/profile/setup/availability.tsx
  packages/web/pages/profile/setup/complete.tsx
  packages/web/pages/profile/setup/memberships.tsx
  packages/web/pages/profile/setup/personalityType.tsx
  packages/web/pages/profile/setup/playerType.tsx
  packages/web/pages/profile/setup/skills.tsx
  packages/web/pages/profile/setup/timeZone.tsx
  packages/web/pages/profile/setup/username.tsx
  packages/web/utils/dateHelpers.ts
  packages/web/utils/setupOptions.tsx
  yarn.lock
Labels: dependencies

#416 Support connection from smart wallets
  packages/backend/package.json
  packages/backend/src/handlers/auth-webhook/handler.ts
  packages/utils/package.json
  packages/utils/src/did/index.ts
  packages/utils/src/ethereumHelper.ts
  packages/web/contexts/Web3Context.tsx
  packages/web/lib/auth.ts
  packages/web/package.json
  yarn.lock
Labels: WIP, backend, frontend

#417 Spin up a backend in Github Actions for the web build to point to
  .github/workflows/PR-CI.yml
Labels: codebase, ready-for-review

#421 Deploy frontend through render.yaml
  packages/web/config.ts
  render.yaml
Labels: backend

#423 Adding comments to silence eslint
  packages/@types/3box/index.d.ts
  packages/backend/src/handlers/actions/migrateSourceCredAccounts/handler.ts
  packages/backend/src/handlers/actions/updateBoxProfile/updateVerifiedAccounts.ts
  packages/backend/src/handlers/triggers/types.ts
  packages/backend/src/index.ts
  packages/metamaps/redux/ThreeBox.tsx
  packages/utils/src/did/index.ts
  packages/web/contexts/Web3Context.tsx
Labels: codebase, ready-for-review
