Repository MetaFam/TheGame, pull requests merged in 2022-06, with the labels that each got.

#1289 Fixing changed parameter for `busboy.on('file')`
  packages/web/lib/hooks/useUser.ts
  packages/web/pages/api/storage.ts
Labels: backend, bug-fix

#1285 Fix the XP command on the discord bot
  packages/discord-bot/src/discord/commands/getXp.ts
Labels: bug-fix

#1290 switched pSEED to Polygon
  packages/backend/codegen.yml
  packages/backend/src/config.ts
  packages/backend/src/handlers/actions/quests/createQuest/permissions.ts
  packages/backend/src/handlers/auth-webhook/handler.ts
  packages/backend/src/lib/ethereum.ts
Labels: backend, frontend, Hasura, quests
